[config]
delimeter = "-"
extension = ".out"
directory = "bin"
logging = false
example_input_file = "exampleTestCases.txt"
process_counts = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
thread_counts = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
